name: Hola mundo

on:
  workflow_dispatch: # ejecución manual

  push: # Cuando nuestro proyecto reciba cambios ejecutamos
    branches: # Qué ramas deben ejecutar el workflow
      - main

    paths: # Qué rutas modificadas disparan el workflow
      - 'BibliotecaAPI/**'
      - 'BibliotecaAPITests/**'
      - '.github/workflows/hola-mundo.yml'

  pull_request: # Ejecutar cuando haya una PR hacia main
    branches:
      - main

jobs:
  saludar:
    runs-on: ubuntu-latest

    steps:
      - name: Muestra mensaje hola mundo
        run: echo "hola mundo, Cucho!!"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Listar los archivos del repo
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguientes archivos:"
          tree
